# AWS Region
REGION ?= $(shell aws configure get region || echo "us-east-1") 

# The Environment, i.e dev/qa/prod
ENV ?= $(shell aws configure get env || echo "prod")

# The deploy color
COLOR ?= $(shell aws configure get deploy-color || echo "blue")

# Account
ACCOUNT ?= $(shell aws configure get account|| echo "githubActions")
## get dir
MAKEFILE_DIR := $(dir $(abspath $(lastword $(MAKEFILE_LIST))))
# Terraform Variables
VAR_FILE ?= $(MAKEFILE_DIR)vars/$(ACCOUNT)-$(ENV)-$(COLOR)-$(REGION).tfvars

ServiceName ?= $(shell grep '^ServiceName' $(VAR_FILE) | sed 's/.*= *"//;s/"//')
STATE_STORE ?= $(shell grep '^STATE_STORE' $(VAR_FILE) | sed 's/.*= *"//;s/"//')
ROLE_ARN    ?= $(shell grep '^ROLE_ARN' $(VAR_FILE) | sed 's/.*= *"//;s/"//')

print_var_file:
	@echo $(VAR_FILE)


include $(VAR_FILE)

_var_file:
	@$(MAKE) _workspace_create ws=$(AccountName)-$(ENV)-$(COLOR)-$(REGION)
	@echo "Using var file $(VAR_FILE)"

_workspace_create:
	@terraform workspace new $(ws) > /dev/null 2>&1 || terraform workspace select $(ws) > /dev/null 2>&1 || true
	#@try {terraform workspace new $ws *>$null -or terraform workspace select $ws *>$null} catch {# Silently continue}
_workspace_show:
	@echo "Using workspace:"
	@terraform workspace show

_create_state_bucket:
	@printf "terraform { \nbackend \"s3\" { \nbucket=\"$(STATE_STORE)\" \nkey=\"$(ServiceName)/root_tfstate.json\" \nregion=\"$(REGION)\" \nassume_role = { \nrole_arn = \"$(ROLE_ARN)\" \n} \n} \n}" > backend.tf

_tf_init:
	@terraform init -var-file=$(VAR_FILE)

_check_init:
	@if [ -d ".terraform" ]; then if [ -f "backend.tf" ]; then echo "Terraform init exists."; else make _create_state_bucket; fi; else make init; fi

init: _create_state_bucket _tf_init _var_file _workspace_show

create: init apply

_plan: init _check_init _var_file
	@terraform plan -var-file=$(VAR_FILE)

plan: init _check_init _var_file
	@terraform plan -out=plan.tfplan -var-file=$(VAR_FILE)

apply: _check_init _var_file
	@terraform apply -var-file=$(VAR_FILE)

delete: _check_init _var_file
	@terraform destroy -var-file=$(VAR_FILE) -lock=false
	
output:
	@terraform output

clean:
	@rm -rf backend*.tf
	@rm -rf .terraform
	@rm -rf terraform.tfstate.*